language: python
python:
  - "3.3"
# command to install dependencies
# install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script:
  - nosetests --with-coverage --with-profile --with-id --verbosity=2 -w unitTest unitTest/common
