language: python
python:
  - "3.3"
#  - "3.4"
#  - pypy3
install:
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=myapp tests/all_test.py
  - coverage report -m
after_success:
  coveralls --verbose
